const std = @import("std");

const cString = @cImport({
    @cInclude("string.h");
});

const hs = @cImport({
    @cInclude("hs/hs.h");
});

const check = @import("../common.zig").check;
const Database = @import("database.zig").Database;
const Pattern = @import("../compile/pattern.zig");
const runtime = @import("../runtime.zig");
const ScanOptions = @import("../runtime.zig").ScanOptions;

buf: []u8,
owned: bool = false,

const Serialized = @This();

pub fn init(buf: []u8) Serialized {
    return Serialized{
        .buf = buf,
    };
}

pub fn deinit(self: *const Serialized) void {
    if (self.owned) {
        std.c.free(self.buf.ptr);
    }
}

/// Serialize a pattern database to a stream of bytes.
pub fn serialize(db: *const Database) !Serialized {
    var buf: ?*const u8 = null;
    var sz: usize = 0;

    try check(hs.hs_serialize_database(@ptrCast(db.ptr), @ptrCast(&buf), &sz));

    return if (buf) |ptr| Serialized{
        .buf = @constCast(@as([*]const u8, @ptrCast(ptr))[0..sz]),
        .owned = true,
    } else error.UnknownError;
}

/// Reconstruct a pattern database from a stream of bytes previously generated by `serialize`.
pub fn deserialize(self: *const Serialized) !Database {
    var db: ?*hs.hs_database_t = null;

    try check(hs.hs_deserialize_database(self.buf.ptr, self.buf.len, &db));

    return if (db) |ptr| Database{
        .ptr = @ptrCast(ptr),
    } else error.UnknownError;
}

/// Utility function for reporting the size that would be required by a database if it were deserialized.
pub fn databaseSize(self: *const Serialized) !usize {
    var sz: usize = 0;

    try check(hs.hs_serialized_database_size(self.buf.ptr, self.buf.len, &sz));

    return sz;
}

/// Utility function providing information about a serialized database.
pub fn databaseInfo(self: *const Serialized, allocator: std.mem.Allocator) ![]const u8 {
    var db_info: ?[*]u8 = null;

    try check(hs.hs_serialized_database_info(self.buf.ptr, self.buf.len, &db_info));
    defer std.c.free(db_info);

    return if (db_info) |p|
        allocator.dupe(u8, p[0..cString.strlen(p)])
    else
        error.UnknownError;
}

// ===== Unit Tests =====

test init {
    var test_buf = [_]u8{ 1, 2, 3, 4, 5 };
    const serialized = Serialized.init(&test_buf);

    try std.testing.expectEqualSlices(u8, &test_buf, serialized.buf);
    try std.testing.expect(!serialized.owned);
}

test serialize {
    const pattern = try Pattern.parse("hello");
    const db = try Database.compile(&pattern, .{});
    defer db.deinit();

    const serialized = try Serialized.serialize(&db);
    defer serialized.deinit();

    try std.testing.expect(serialized.buf.len > 0);
    try std.testing.expect(serialized.owned);
}

test deserialize {
    const pattern = try Pattern.parse("world");
    const db = try Database.compile(&pattern, .{});
    defer db.deinit();

    const serialized = try Serialized.serialize(&db);
    defer serialized.deinit();

    const deserialized_db = try serialized.deserialize();
    defer deserialized_db.deinit();

    // Verify the deserialized database is valid
    // Database no longer has a mode field, just verify both databases are valid
    const db_size = try db.size();
    const deserialized_size = try deserialized_db.size();
    try std.testing.expect(db_size > 0);
    try std.testing.expect(deserialized_size > 0);
}

test "serialize and deserialize round trip" {
    const pattern = try Pattern.parse("test.*pattern");
    const db = try Database.compile(&pattern, .{});
    defer db.deinit();

    // Serialize the database
    const serialized = try Serialized.serialize(&db);
    defer serialized.deinit();

    // Deserialize it back
    const deserialized_db = try serialized.deserialize();
    defer deserialized_db.deinit();

    // Test that both databases work the same way
    const scratch1 = try db.allocScratch();
    defer scratch1.deinit();

    const scratch2 = try deserialized_db.allocScratch();
    defer scratch2.deinit();

    var match_count1: u32 = 0;
    var match_count2: u32 = 0;

    const opts1 = ScanOptions{
        .onEvent = struct {
            fn handler(evt: runtime.MatchEvent) !void {
                evt.data(u32).* += 1;
            }
        }.handler,
        .context = &match_count1,
    };

    const opts2 = ScanOptions{
        .onEvent = struct {
            fn handler(evt: runtime.MatchEvent) !void {
                evt.data(u32).* += 1;
            }
        }.handler,
        .context = &match_count2,
    };

    const test_data = "this is a test pattern match";

    try db.scanBlock(test_data, scratch1, opts1);
    try deserialized_db.scanBlock(test_data, scratch2, opts2);

    try std.testing.expectEqual(match_count1, match_count2);
    try std.testing.expect(match_count1 > 0);
}

test databaseSize {
    const pattern = try Pattern.parse("size.*test");
    const db = try Database.compile(&pattern, .{});
    defer db.deinit();

    const serialized = try Serialized.serialize(&db);
    defer serialized.deinit();

    const size = try serialized.databaseSize();

    try std.testing.expect(size > 0);
    try std.testing.expectEqual(serialized.buf.len, size);
}

test databaseInfo {
    const pattern = try Pattern.parse("info.*test");
    const db = try Database.compile(&pattern, .{});
    defer db.deinit();

    const serialized = try Serialized.serialize(&db);
    defer serialized.deinit();

    const info = try serialized.databaseInfo(std.testing.allocator);
    defer std.testing.allocator.free(info);

    // Should contain version information
    try std.testing.expect(std.mem.containsAtLeast(u8, info, 1, "Version"));
    try std.testing.expect(info.len > 0);
}

test "serialize with different modes" {
    const pattern = try Pattern.parse("mode.*test");

    // Test block mode
    {
        const db = try Database.compile(&pattern, .{ .mode = .{ .block = true } });
        defer db.deinit();

        const serialized = try Serialized.serialize(&db);
        defer serialized.deinit();

        const deserialized_db = try serialized.deserialize();
        defer deserialized_db.deinit();

        try std.testing.expect(try deserialized_db.size() > 0);
    }

    // Test stream mode
    {
        const db = try Database.compile(&pattern, .{ .mode = .{ .stream = true } });
        defer db.deinit();

        const serialized = try Serialized.serialize(&db);
        defer serialized.deinit();

        const deserialized_db = try serialized.deserialize();
        defer deserialized_db.deinit();

        try std.testing.expect(try deserialized_db.size() > 0);
    }

    // Test vectored mode
    {
        const db = try Database.compile(&pattern, .{ .mode = .{ .vectored = true } });
        defer db.deinit();

        const serialized = try Serialized.serialize(&db);
        defer serialized.deinit();

        const deserialized_db = try serialized.deserialize();
        defer deserialized_db.deinit();

        try std.testing.expect(try deserialized_db.size() > 0);
    }
}

test "serialize with multiple patterns" {
    const patterns = [_]Pattern{
        try Pattern.parse("first"),
        try Pattern.parse("second"),
        try Pattern.parse("third"),
    };

    const db = try Database.compileMulti(&patterns, .{});
    defer db.deinit();

    const serialized = try Serialized.serialize(&db);
    defer serialized.deinit();

    const deserialized_db = try serialized.deserialize();
    defer deserialized_db.deinit();

    // Test that the deserialized database works with multiple patterns
    const scratch = try deserialized_db.allocScratch();
    defer scratch.deinit();

    var match_count: u32 = 0;
    const opts = ScanOptions{
        .onEvent = struct {
            fn handler(evt: runtime.MatchEvent) !void {
                evt.data(u32).* += 1;
            }
        }.handler,
        .context = &match_count,
    };

    try deserialized_db.scanBlock("first second third", scratch, opts);
    try std.testing.expect(match_count >= 3);
}

test "serialize with literal mode" {
    const pattern = try Pattern.parse("literal.*test");
    const db = try Database.compile(&pattern, .{ .literal = true });
    defer db.deinit();

    const serialized = try Serialized.serialize(&db);
    defer serialized.deinit();

    const deserialized_db = try serialized.deserialize();
    defer deserialized_db.deinit();

    // Test that literal mode is preserved
    const scratch = try deserialized_db.allocScratch();
    defer scratch.deinit();

    var match_found = false;
    const opts = ScanOptions{
        .onEvent = struct {
            fn handler(evt: runtime.MatchEvent) !void {
                evt.setData(bool, true);
            }
        }.handler,
        .context = &match_found,
    };

    // Should match literal string
    try deserialized_db.scanBlock("literal.*test", scratch, opts);
    try std.testing.expect(match_found);

    // Should not match regex patterns
    match_found = false;
    try deserialized_db.scanBlock("literal123test", scratch, opts);
    try std.testing.expect(!match_found);
}

test "serialize error handling" {
    // Test with invalid pattern database (this should not happen in practice)
    // but we can test the error handling path
    var invalid_buf = [_]u8{ 0, 1, 2, 3, 4, 5, 6, 7, 8, 9 };
    const serialized = Serialized.init(&invalid_buf);

    // This should fail when trying to deserialize invalid data
    try std.testing.expectError(error.Invalid, serialized.deserialize());
}

test "databaseSize with invalid data" {
    var invalid_buf = [_]u8{ 0, 1, 2, 3, 4, 5, 6, 7, 8, 9 };
    const serialized = Serialized.init(&invalid_buf);

    // This should fail when trying to get size of invalid data
    try std.testing.expectError(error.Invalid, serialized.databaseSize());
}

test "databaseInfo with invalid data" {
    var invalid_buf = [_]u8{ 0, 1, 2, 3, 4, 5, 6, 7, 8, 9 };
    const serialized = Serialized.init(&invalid_buf);

    // This should fail when trying to get info of invalid data
    try std.testing.expectError(error.Invalid, serialized.databaseInfo(std.testing.allocator));
}

test "serialize with complex patterns" {
    const complex_patterns = [_]Pattern{
        try Pattern.parse("\\d{4}-\\d{2}-\\d{2}"), // Date pattern
        try Pattern.parse("[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}"), // Email pattern
        try Pattern.parse("\\b(?:https?://|www\\.)[^\\s]+"), // URL pattern
    };

    const db = try Database.compileMulti(&complex_patterns, .{});
    defer db.deinit();

    const serialized = try Serialized.serialize(&db);
    defer serialized.deinit();

    const deserialized_db = try serialized.deserialize();
    defer deserialized_db.deinit();

    // Test that complex patterns work after serialization
    const scratch = try deserialized_db.allocScratch();
    defer scratch.deinit();

    var match_count: u32 = 0;
    const opts = ScanOptions{
        .onEvent = struct {
            fn handler(evt: runtime.MatchEvent) !void {
                evt.data(u32).* += 1;
            }
        }.handler,
        .context = &match_count,
    };

    const test_data = "Contact us at test@example.com or visit https://example.com on 2024-01-01";
    try deserialized_db.scanBlock(test_data, scratch, opts);
    try std.testing.expect(match_count >= 3);
}

test "serialize with flags" {
    const pattern = try Pattern.parse("test.*pattern");
    const db = try Database.compile(&pattern, .{
        .mode = .{ .stream = true },
        .literal = true,
    });
    defer db.deinit();

    const serialized = try Serialized.serialize(&db);
    defer serialized.deinit();

    const deserialized_db = try serialized.deserialize();
    defer deserialized_db.deinit();

    try std.testing.expect(try deserialized_db.size() > 0);
}

test "serialize memory safety" {
    // Test that serialization doesn't leak memory
    const pattern = try Pattern.parse("memory.*test");
    const db = try Database.compile(&pattern, .{});
    defer db.deinit();

    // Serialize and deserialize multiple times
    for (0..10) |_| {
        const serialized = try Serialized.serialize(&db);
        defer serialized.deinit();

        const deserialized_db = try serialized.deserialize();
        defer deserialized_db.deinit();

        try std.testing.expect(try deserialized_db.size() > 0);
    }
}

test "serialize with empty patterns" {
    const empty_pattern = Pattern.init("", .{ .allow_empty = true });
    const db = try Database.compile(&empty_pattern, .{});
    defer db.deinit();

    const serialized = try Serialized.serialize(&db);
    defer serialized.deinit();

    const deserialized_db = try serialized.deserialize();
    defer deserialized_db.deinit();

    try std.testing.expect(try deserialized_db.size() > 0);
}

test "serialize with single character patterns" {
    const single_char_pattern = try Pattern.parse("a");
    const db = try Database.compile(&single_char_pattern, .{});
    defer db.deinit();

    const serialized = try Serialized.serialize(&db);
    defer serialized.deinit();

    const deserialized_db = try serialized.deserialize();
    defer deserialized_db.deinit();

    // Test that single character patterns work
    const scratch = try deserialized_db.allocScratch();
    defer scratch.deinit();

    var match_found = false;
    const opts = ScanOptions{
        .onEvent = struct {
            fn handler(evt: runtime.MatchEvent) !void {
                evt.setData(bool, true);
            }
        }.handler,
        .context = &match_found,
    };

    try deserialized_db.scanBlock("a", scratch, opts);
    try std.testing.expect(match_found);
}
