# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    paths-ignore:
      - "**.md"
  pull_request:
    paths-ignore:
      - "**.md"
  workflow_dispatch:

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        zig: [0.15.1]
    runs-on: ${{matrix.os}}
    steps:
      - name: Install Linux dependencies
        if: startsWith(matrix.os, 'ubuntu-')
        run: |
          sudo apt-get update
          sudo apt-get install -yq libhyperscan-dev libpcap-dev pkg-config
      - name: Install MacOS dependencies
        if: startsWith(matrix.os, 'macos-')
        run: |
          brew install vectorscan pkg-config libpcap
      - run: |
          git config --global core.ignorecase false
      - uses: actions/checkout@v5
      - uses: mlugg/setup-zig@v2
        with:
          version: ${{matrix.zig}}
      - run: zig build test --summary all

  lint:
    runs-on: ubuntu-latest
    steps:
      - run: |
          sudo apt-get update
          sudo apt-get install -yq libhyperscan-dev
      - run: |
          git config --global core.ignorecase false
      - uses: actions/checkout@v5
      - uses: mlugg/setup-zig@v2
      - run: zig build lint
